# Generated by Django 4.1.3 on 2022-12-01 08:57

import django.core.validators
from django.db import migrations, models
import fileConvert.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdffile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to=fileConvert.models.set_pdf_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('filename', models.CharField(max_length=20)),
                ('pagenumforcover', models.IntegerField()),
                ('coverpage', models.FileField(upload_to=fileConvert.models.set_cover_file_name)),
            ],
        ),
    ]
